---
- hosts: ancalagon
  tasks:

    - name: Install core development packages
      pacman:
        name:
          - python
          - python2
          - sudo
          - git
          - emacs
          - vim
          - htop
          - iotop
          - base-devel
      become: yes
      become_method: su
